Add deployment example for Kubernetes and Docker
grafana/synthetic-monitoring-agent pull request #81
Opened 2020-09-23 20:01 UTC by electron0zero

Fixes #80

2020-09-24 18:41 UTC, mem requested changes

2020-09-24 18:41 UTC, mem commented on README.md
> +Now you should have agent reporting as private probe, and running checks(if you have assigned) in logs.
```suggestion
Now you should have the agent reporting as private probe, and running checks (if you have created some) in the logs.
```

2020-09-24 18:41 UTC, mem commented on README.md
> +See [examples/kubernetes](./examples/kubernetes) for Docs and example yaml files
```suggestion
See [examples/kubernetes](./examples/kubernetes) for documentation and example yaml files
```

2020-09-24 18:41 UTC, mem commented on examples/kubernetes/README.md
> +- Get Probe Authentication Token for your private probe, [see steps](https://grafana.com/docs/grafana-cloud/synthetic-monitoring/private-probes/)
```suggestion
- Get a probe Authentication Token for your private probe, [see here for steps](https://grafana.com/docs/grafana-cloud/synthetic-monitoring/private-probes/)
```

2020-09-24 18:41 UTC, mem commented on examples/kubernetes/README.md
> +- Replace `YOUR_TOKEN_HERE` in [secret.yaml](secret.yaml) with your Probe Authentication Token
```suggestion
- Replace `YOUR_TOKEN_HERE` in [secret.yaml](secret.yaml) with your probe Authentication Token
```

2020-09-24 18:41 UTC, mem commented on examples/kubernetes/README.md
> +- Apply [namespace.yaml](namespace.yaml) to create `synthetic-monitoring` namespace
```suggestion
- Apply [namespace.yaml](namespace.yaml) to create the `synthetic-monitoring` namespace
```

2020-09-24 18:41 UTC, mem commented on examples/kubernetes/README.md
> +- Apply [secret.yaml](secret.yaml) to create `sm-agent-1` secret
```suggestion
- Apply [secret.yaml](secret.yaml) to create the `sm-agent-1` secret
```

2020-09-24 18:41 UTC, mem commented on examples/kubernetes/README.md
> +- Now we will apply [deployment.yaml](deployment.yaml) to deploy out agent
```suggestion
- Apply [deployment.yaml](deployment.yaml) to deploy your agent
```

2020-09-24 18:41 UTC, mem commented on examples/kubernetes/README.md
> +Now you should have agent reporting as private probe.
```suggestion
Now you should have the agent reporting as private probe.
```

2020-09-24 18:41 UTC, mem commented on examples/kubernetes/README.md
> +If you are running it in production, you should pin the image version instead of `latest`,
```suggestion
If you are running it in production, you should pin the image to an specific version instead of `latest`,
```

2020-09-24 18:41 UTC, mem commented on examples/kubernetes/README.md
> +We expose Prometheus style metrics (/metrics endpoint) on port 4050 of process(and pod),
```suggestion
The process exposes Prometheus-style metrics on an HTTP server running on port 4050 (/metrics endpoint).
```

2020-09-24 18:41 UTC, mem commented on examples/kubernetes/README.md
> +you can scrape and monitor your private probe
```suggestion
You can scrape and monitor your private probe in this way using either Prometheus or the Grafana Cloud Agent.
```

2020-09-24 19:11 UTC, electron0zero commented on README.md
> +export API_TOKEN=YOUR_TOKEN_HERE
makes sense, updated it :+1:

2020-09-25 21:07 UTC, mem approved these changes

2020-09-25 21:08 UTC, merged